# Generated by Django 4.1 on 2023-12-12 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_choiceforeasyq_choiceforhardq_choiceformediumq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.category'),
        ),
        migrations.AddField(
            model_name='hardquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.category'),
        ),
        migrations.AddField(
            model_name='mediumquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.category'),
        ),
    ]
