# Generated by Django 4.1 on 2023-12-12 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_easyquestion_category_hardquestion_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easyquestion',
            name='category',
            field=models.ForeignKey(blank=True, default='Coding', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.category'),
        ),
        migrations.AlterField(
            model_name='hardquestion',
            name='category',
            field=models.ForeignKey(blank=True, default='Coding', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.category'),
        ),
        migrations.AlterField(
            model_name='mediumquestion',
            name='category',
            field=models.ForeignKey(blank=True, default='Coding', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.category'),
        ),
    ]
