# Generated by Django 4.1 on 2023-12-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_choiceforeasyq_choiceforhardq_choiceformediumq_and_more'),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.profile')),
            ],
            options={
                'unique_together': {('category',)},
            },
        ),
        migrations.CreateModel(
            name='TestScoresLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='ExperiencePoints',
        ),
    ]
