# Generated by Django 4.1 on 2023-12-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_easyquestion_category_hardquestion_category_and_more'),
        ('user_profiles', '0002_averagescores_testscoreslibrary_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='averagescores',
            unique_together={('category', 'profile')},
        ),
    ]
