# Generated by Django 4.1 on 2023-12-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_easyquestion_category_and_more'),
        ('user_profiles', '0003_alter_averagescores_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AverageScores',
            new_name='AverageScore',
        ),
    ]
