# Generated by Django 4.1 on 2023-12-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_testmarkslibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmarkslibrary',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
