# Generated by Django 4.1 on 2023-12-23 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_combinedtestcategory'),
        ('user_profiles', '0006_testmarkslibrary_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedTestScoresLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.combinedtestcategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.profile')),
            ],
        ),
    ]
