# Generated by Django 4.1 on 2023-12-24 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('description', models.TextField()),
                ('easy_test_file', models.FileField(upload_to='media/test_files/')),
                ('medium_test_file', models.FileField(upload_to='media/test_files/')),
                ('hard_test_file', models.FileField(upload_to='media/test_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='GroupTestMediumQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.ForeignKey(blank=True, default='Coding', null=True, on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptestcategory')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptest')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTestHardQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.ForeignKey(blank=True, default='Coding', null=True, on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptestcategory')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptest')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTestEasyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.ForeignKey(blank=True, default='Coding', null=True, on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptestcategory')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptest')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTestCombinedTestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('associated_categories', models.ManyToManyField(to='group_tests.grouptestcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTestChoiceForMediumQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptestmediumquestion')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTestChoiceForHardQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptesthardquestion')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTestChoiceForEasyQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptesteasyquestion')),
            ],
        ),
        migrations.AddField(
            model_name='grouptest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptestcategory'),
        ),
    ]
