# Generated by Django 4.1 on 2023-12-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_tests', '0002_grouptest_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouptest',
            old_name='password',
            new_name='has_password',
        ),
        migrations.RenameField(
            model_name='grouptestcombinedcategory',
            old_name='password',
            new_name='has_password',
        ),
    ]
