# Generated by Django 4.1 on 2023-12-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_tests', '0003_grouptest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptest',
            name='difficulty',
        ),
    ]
