# Generated by Django 4.1 on 2023-12-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_tests', '0004_remove_grouptest_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptest',
            name='password',
        ),
    ]
