# Generated by Django 4.1 on 2023-12-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_tests', '0005_remove_grouptest_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupTestChoiceForMediumQ',
            new_name='ChoiceForEasyQ',
        ),
        migrations.RenameModel(
            old_name='GroupTestChoiceForHardQ',
            new_name='ChoiceForHardQ',
        ),
        migrations.RenameModel(
            old_name='GroupTestChoiceForEasyQ',
            new_name='ChoiceForMediumQ',
        ),
        migrations.RenameModel(
            old_name='GroupTestHardQuestion',
            new_name='EasyQuestion',
        ),
        migrations.RenameModel(
            old_name='GroupTestMediumQuestion',
            new_name='HardQuestion',
        ),
        migrations.RenameModel(
            old_name='GroupTestEasyQuestion',
            new_name='MediumQuestion',
        ),
    ]
